# Generated by Django 5.2.15 on 2026-07-05 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('capacite_wh', models.FloatField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tarifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regle', models.TextField()),
                ('prix_par_wh', models.FloatField()),
                ('date_modif', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarifs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_chassis', models.CharField(max_length=30, unique=True)),
                ('modele', models.CharField(blank=True, max_length=60, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.clients')),
            ],
            options={
                'db_table': 'motos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_depart', models.FloatField()),
                ('pct_cible', models.FloatField()),
                ('energie_wh', models.FloatField(blank=True, null=True)),
                ('cout_fcfa', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(max_length=15)),
                ('date_heure', models.DateTimeField(blank=True, null=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.motos')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.stations')),
                ('tarif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tarifs')),
            ],
            options={
                'db_table': 'sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paiements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('numero_momo', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(max_length=7)),
                ('date_heure', models.DateTimeField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.sessions')),
            ],
            options={
                'db_table': 'paiements',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=5)),
                ('actif', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.stations')),
            ],
            options={
                'db_table': 'utilisateurs',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tarifs',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.utilisateurs'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.utilisateurs'),
        ),
    ]
